### ISSUE TITLE
Pre-lab feedback

### ISSUE THREAD

**Issue by srchi** [Microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#14]
Can we have a ARM script to deploy these resources, instead of manually having to create them on the portal?

**Comment by tsander26** [comment]
I think it is good that we force the user to deploy these resources. An ARM script would be good but it does take away some of the lab's effectiveness in giving the user a complete experience. However, I think we could re-order the steps in the prelab to minimize time waiting for services to be deployed. For example, switch Task 10 and Task 11 in the pre-lab so that we aren't waiting for Task 8 to finish. It also might make sense to move Task 1 to be after Task 7 (with the other Azure portal actions).
