### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#44]

**Comment by timahenning** [comment]
Need to add HTAP.

**Comment by joelhulen** [comment]
Suggestions for the June 2020 update:

- Integrate Azure Synapse Link for Azure Cosmos DB (HTAP) to the WDS
- Add scenario for Azure Synapse Analytics to the WDS
- Update Power BI reports
- Update all screenshots, due to portal UI changes
- Update library versions in Notebooks
- Update console project SDK versions

**Comment by AnithaAdusumilli** [comment]
Suggestions for Synapse Link; 
- Integrate Azure Synapse Link for Azure Cosmos DB (HTAP) to the WDS and HOL
          - Below scenarios: 
                  -	Synapse Link – Spark – ML (instead of Databricks Delta)
                  -	Synapse Link – SQL – Power BI (instead of explicit ETL to ADLS)
                  -	Write back the aggregation results to Cosmos DB OLTP as serving layer from Synapse

**Comment by DawnmarieDesJardins** [comment]
Closing with merge of PR #45
