### ISSUE TITLE
Sept 2021 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Cosmos-DB-Real-Time-Advanced-Analytics#57]

**Comment by joelhulen** [comment]
* Enable autoscale on the Cosmos DB containers
* Use Jupyter notebook on Cosmos DB for continuous performance tests using bokeh plots with error bars
* Add segment about data backups to the WDS - should we focus on **continuous backups**, which are still in private preview?
* Update Power BI reports
* Update all screenshots, due to portal UI changes
* Update all Synapse screenshots due to Synapse Studio UI changes
* Update library versions in Notebooks
* Update console project SDK versions

**Comment by GaryHopeMS** [comment]
- Create clear delineation of the real-time vs batch scoring workflows end-to-end. Highlight the various data flows and the problems they solve. The direction of data movement vs application calls is somewhat confusing.
- Visually show transactional and analytical store data in the same Cosmos DB service, they are separated in diagrammatically and create conceptual understanding problems. 
- Move the comparison of using event-hubs vs Cosmos DB from the first exercise to the last (it can be marked as optional). The value of using Event Hubs and Cosmos DB together is more important than comparing the two.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #58
